environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test

cache:
  - node_modules -> package.json